name: lls
markdown: kramdown
kramdown:
  hard_wrap: true
  # syntax_highlighter: rouge
  # syntax_highlighter_opts:
  #   css_class: 'highlight'
  #   span:
  #     line_numbers: false
  #   block:
  #     line_numbers: true
permalink: /blog/:year/:month/:day/:title
highlighter: rouge
