name: lls
markdown: kramdown
kramdown:
  hard_wrap: true
  highlighter: rouge
  syntax_highlighter_opts:
      block:
          line_numbers: true
  #   css_class: 'highlight'
  #   span:
  #     line_numbers: false
permalink: /blog/:year/:month/:day/:title
highlighter: rouge
